repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
    args:
    - --fix=lf
  - id: trailing-whitespace
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-yaml
- repo: https://github.com/lovesegfault/beautysh
  rev: v6.4.3
  hooks:
  - id: beautysh
    args:
    - --indent-size
    - '4'
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.11.0.1-1
  hooks:
  - id: shellcheck
    args:
    - --severity=error
- repo: https://github.com/executablebooks/mdformat
  rev: 1.0.0
  hooks:
  - id: mdformat
    args:
    - --end-of-line
    - lf
    additional_dependencies:
    - mdformat-gfm
    - mdformat-frontmatter
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.49.1
  hooks:
  - id: markdownlint
